paths:
  /healthcheck:
    get:
      x-fern-ignore: true
  /auth/callback:
    get:
      x-fern-ignore: true
  /auth/url:
    get:
      x-fern-ignore: true
  /auth/session:
    get:
      x-fern-ignore: true
  /auth/user:
    get:
      x-fern-ignore: true
  /user/balance:
    get:
      x-fern-ignore: true
  /instances:
    get:
      x-fern-sdk-group-name: instances
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name: instances
      x-fern-sdk-method-name: create
  /instances/{instance_id}:
    delete:
      x-fern-sdk-group-name: instances
      x-fern-sdk-method-name: delete
  /ssh_keys:
    get:
      x-fern-sdk-group-name: ssh_keys
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name: ssh_keys
      x-fern-sdk-method-name: create
  /ssh_keys/{ssh_key_id}:
    delete:
      x-fern-sdk-group-name: ssh_keys
      x-fern-sdk-method-name: delete
  /api_keys:
    get:
      x-fern-ignore: true
    post:
      x-fern-ignore: true
  /api_keys/{api_key_id}:
    delete:
      x-fern-ignore: true
  /list_available_configurations:
    get:
      x-fern-sdk-group-name: configurations
      x-fern-sdk-method-name: list
  /list_user_ssh_keys:
    get:
      x-fern-ignore: true
    post:
      x-fern-ignore: true
  /list_user_ssh_keys/{ssh_key_id}:
    delete:
      x-fern-ignore: true
  /list_available_os_templates:
    get:
      x-fern-sdk-group-name: templates
      x-fern-sdk-method-name: list
  /payments/create-intent:
    post:
      x-fern-ignore: true
  /webhooks/stripe/payment_completed:
    post:
      x-fern-ignore: true

x-fern-global-headers:
  - header: api-key
    env: FLUIDSTACK_API_KEY

servers: 
- url: https://platform.fluidstack.io
  x-fern-server-name: Production