// This file was auto-generated by Fern from our API Definition.

package client

import (
	configurations "go-mod-path/generated/go/configurations"
	core "go-mod-path/generated/go/core"
	instances "go-mod-path/generated/go/instances"
	option "go-mod-path/generated/go/option"
	sshkeys "go-mod-path/generated/go/sshkeys"
	templates "go-mod-path/generated/go/templates"
	http "net/http"
	os "os"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Instances      *instances.Client
	SshKeys        *sshkeys.Client
	Configurations *configurations.Client
	Templates      *templates.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.ApiKey == "" {
		options.ApiKey = os.Getenv("FLUIDSTACK_API_KEY")
	}
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:         options.ToHeader(),
		Instances:      instances.NewClient(opts...),
		SshKeys:        sshkeys.NewClient(opts...),
		Configurations: configurations.NewClient(opts...),
		Templates:      templates.NewClient(opts...),
	}
}
